FROM node:alpine AS builder

WORKDIR /app
COPY package*.json .
RUN npm install
RUN npm install typescript -g
COPY . .
RUN npx tsc 

FROM node:alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY package*.json ./
ENV NODE_ENV=production
RUN npm install --omit=dev

CMD ["node", "./dist/src/index.js"]