apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: guilhermebarroso/auth
          resources:
            requests:
              memory: "128Mi" # Request 256 megabytes of memory
              cpu: "100m"     # Request 100 milliCPU (0.1 CPU core)
            limits:
              memory: "128Mi" # Limit memory usage to 256 megabytes
              cpu: "100m"     # Limit CPU usage to 200 milliCPU
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: "mongodb://auth-mongo-srv:27017/auth"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort : 3000